# Generated by Django 4.1.3 on 2024-05-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorismi', models.CharField(max_length=70)),
                ('slug', models.SlugField(default='', max_length=70, unique=True)),
            ],
        ),
    ]
