# Generated by Django 4.1.3 on 2024-05-22 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_orderitem_delete_sepet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
